name:                treegraphics
version:             0.1.0.0
github:              "EgorLappo/treegraphics"
license:             BSD3
author:              "Egor Lappo"
maintainer:          "egor@ccrma.stanford.edu"
copyright:           "Copyright (c) 2022 Egor Lappo"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/EgorLappo/treegraphics#readme>

dependencies:
- base >= 4.7 && < 5
- diagrams-lib
- diagrams-svg

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wno-incomplete-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-unused-do-bind

library:
  source-dirs: src
  default-extensions:
    - NoMonomorphismRestriction
    - FlexibleContexts
    - TypeFamilies
    - LambdaCase

executables:
  treegraphics-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    default-extensions:
      - NoMonomorphismRestriction
      - FlexibleContexts
      - TypeFamilies
      - LambdaCase
    dependencies:
    - treegraphics

